################################
# Tipos de validación
################################


validator.type = public, restricted, nonpublic, public_rec, restricted_rec, nonpublic_rec
validator.defaultType = public
################################
# Etiquetas UI
################################

validator.typeLabel.public = Health DCAT-AP – Acceso público
validator.typeLabel.restricted = Health DCAT-AP – Acceso restringido
validator.typeLabel.nonpublic = Health DCAT-AP – Acceso no público

validator.typeLabel.public_rec = Health DCAT-AP público (con recomendadas)
validator.typeLabel.restricted_rec = Health DCAT-AP restringido (con recomendadas)
validator.typeLabel.nonpublic_rec = Health DCAT-AP no público (con recomendadas)

################################
# SHACL obligatorios
################################

validator.shaclFile.public = shapes/common/range.ttl,shapes/common/mdr-vocabularies.shape.ttl,shapes/public/public-shapes.ttl

validator.shaclFile.restricted = shapes/common/range.ttl,shapes/common/mdr-vocabularies.shape.ttl,shapes/restricted/restricted-shapes.ttl

validator.shaclFile.nonpublic = shapes/common/range.ttl,shapes/common/mdr-vocabularies.shape.ttl,shapes/non-public/non-public-shapes.ttl

################################
# SHACL obligatorios + recomendados
################################

validator.shaclFile.public_rec = shapes/common/range.ttl,shapes/common/mdr-vocabularies.shape.ttl,shapes/public/public-shapes.ttl,shapes/public/public-shapes_recommended.ttl

validator.shaclFile.restricted_rec = shapes/common/range.ttl,shapes/common/mdr-vocabularies.shape.ttl,shapes/restricted/restricted-shapes.ttl,shapes/restricted/restricted-shapes_recommended.ttl

validator.shaclFile.nonpublic_rec = shapes/common/range.ttl,shapes/common/mdr-vocabularies.shape.ttl,shapes/non-public/non-public-shapes.ttl,shapes/non-public/non-public-shapes_recommended.ttl


################################
# UI
################################

validator.uploadTitle = Health DCAT-AP SHACL Validator
validator.bannerHtml=<div><h1>Health DCAT‑AP Validator</h1><p>Este servicio permite validar conjuntos de datos de salud conforme al perfil Health DCAT‑AP.</p><hr/></div>
validator.footerHtml=<div><hr/><p>Validador experimental – Proyecto Health DCAT‑AP</p></div>

validator.label.additionalInfoLabel = Recurso
validator.reportItemAdditionalInfoTemplate = Dataset [${http://purl.org/dc/terms/title}]
################################
# Metadatos del informe
################################

# Nombre del servicio de validación
validator.report.validationServiceName = Health DCAT-AP Validator

# Versión del validador
validator.report.validationServiceVersion = v1.0

# Nombre general del informe
validator.report.name = Health DCAT-AP validation report

################################
# Perfiles de validación (por tipo)
################################

validator.report.profileId.public = Health DCAT-AP – Público
validator.report.profileId.restricted = Health DCAT-AP – Restringido
validator.report.profileId.nonpublic = Health DCAT-AP – No público
validator.richTextReports = true